---

- name: redis Install | Make sure the redis build dependencies are installed
  apt:
    update_cache: yes
    pkg: "{{item}}"
    state: present
  with_items:
    - build-essential
    - git
    - libjemalloc-dev

- name: redis Install | Make sure repository path exists
  file:
    path: "/tmp/redis-repo"
    state: directory

- name: download redis source
  get_url:
    url: "{{redis_download_url}}"
    dest: "/tmp/redis-src.tar.gz"

- name: redis Install | Clone the redis repo
  command: tar xzf /tmp/redis-src.tar.gz -C /tmp/redis-repo chdir=/tmp

- name: redis Install | make
  command: make chdir=/tmp/redis-repo/redis-{{redis_revision}}

- name: redis Install | make
  command: make install chdir=/tmp/redis-repo/redis-{{redis_revision}}

