---
- name: redis Install | Make sure the redis group is present
  group:
    name: redis
    state: present

- name: redis Install | Make sure the redis user is present
  user:
    name: redis
    group: redis
    shell: /bin/false
    state: present
    system: yes